## Work NoteBook
* This is where I'm testing the pandas python code I'll be putting into the final project notebook. 
* I worked on Arrests on my own and my partner worked on Trees on their own.

---

## Dataset #1

In [18]:
import pandas as pd

# Reading the csv file, displaying first ten values to test it out
arrest_data = pd.read_csv("City of Pittsburgh Arrest Data Set.csv")

arrest_data.head(10)

,_id,PK,CCR,AGE,GENDER,RACE,ARRESTTIME,ARRESTLOCATION,OFFENSES,INCIDENTLOCATION,INCIDENTNEIGHBORHOOD,INCIDENTZONE,INCIDENTTRACT,COUNCIL_DISTRICT,PUBLIC_WORKS_DIVISION,X,Y
0,1,1975272,16158872,42.0,F,B,2016-08-24T12:20:00,"4700 Block Centre AV Pittsburgh, PA 15213",3929 Retail Theft.,"4700 Block Centre AV Pittsburgh, PA 15213",Bloomfield,5,804.0,8.0,2.0,-79.949277,40.452551
1,2,1974456,16144120,31.0,M,W,2016-08-03T14:55:00,"4200 Block Steubenville PKE Pittsburgh, PA 15205",13(a)(16) Possession of Controlled Substance,"4200 Block Steubenville PKE Pittsburgh, PA 15205",Outside City,OSC,5599.0,NaN,NaN,-80.088018,40.440136
2,3,1974466,16144165,63.0,F,B,2016-08-03T16:45:00,"900 Block Freeport RD Fox Chapel, PA 15238",3929 Retail Theft.,"900 Block Freeport RD Fox Chapel, PA 15238",Westwood,5,2811.0,9.0,2.0,-79.891803,40.486625
3,4,1974550,16145257,25.0,F,W,2016-08-05T02:36:00,"Foreland ST & Cedar AV Pittsburgh, PA 15212",5503 Disorderly Conduct. / 5505 Public Drunken...,"Foreland ST & Cedar AV Pittsburgh, PA 15212",East Allegheny,1,2304.0,1.0,1.0,-80.001939,40.454080
4,5,1974596,16145962,25.0,M,B,2016-08-06T02:00:00,"900 Block Woodlow ST Pittsburgh, PA 15205",2702 Aggravated Assault. / 2705 Recklessy Enda...,"900 Block Woodlow ST Pittsburgh, PA 15205",Crafton Heights,5,2814.0,2.0,5.0,-80.052204,40.445900
5,6,1974556,16144301,45.0,M,W,2016-08-15T13:30:00,"600 Block 1st AV Pittsburgh, PA 15219",3929 Retail Theft.,"800 Block Hazelwood AV Pittsburgh, PA 15217",Greenfield,4,1517.0,5.0,3.0,-79.929238,40.419699
6,7,1974628,16147655,29.0,M,W,2016-08-16T13:00:00,"2300 Block Pioneer AV Pittsburgh, PA 15226",2701 Simple Assault.,"2300 Block Pioneer AV Pittsburgh, PA 15226",Brookline,6,1919.0,4.0,5.0,-80.020357,40.400037
7,8,1974607,16146037,21.0,F,B,2016-08-16T04:25:00,"600 Block 1st AV Pittsburgh, PA 15219",2701 Simple Assault. / 5505 Public Drunkenness...,"700 Block S Braddock AV Pittsburgh, PA 15221",Regent Square,4,1410.0,NaN,NaN,-79.834462,40.398957
8,9,1974643,16132537,17.0,M,B,2016-08-29T17:55:00,"1400 Block Washington BL Pittsburgh, PA 15206",903 Criminal Conspiracy. / 3701 Robbery.,"N Euclid AV & Broad ST Pittsburgh, PA 15206",East Liberty,5,1115.0,NaN,NaN,NaN,NaN
9,10,1974647,16138646,14.0,M,B,2016-08-23T13:36:00,Zone 2,3127 Indecent Exposure. / 3123(a)(6) IDSI with...,Zone 5,NaN,5,NaN,NaN,NaN,NaN,NaN

In [51]:
# Count the number of arrests per neighborhood
arrest_counts = arrest_data["INCIDENTNEIGHBORHOOD"].value_counts().sort_values(ascending=True)

# Display the neighborhoods with the least amount of arrests
arrest_counts.head(30)

Mt. Oliver Neighborhood          2
Troy Hill-Herrs Island           6
Mt. Oliver Boro                 18
Central Northside               23
Ridgemont                       37
Regent Square                   37
New Homestead                   39
Swisshelm Park                  43
Chartiers City                  46
East Carnegie                   48
St. Clair                       55
Outside County                  57
Outside State                   67
Summer Hill                     76
Oakwood                         82
Golden Triangle/Civic Arena     83
Hays                           120
Windgap                        124
Mount Oliver                   124
Fairywood                      127
Allegheny West                 130
Arlington Heights              155
Polish Hill                    166
Glen Hazel                     169
Friendship                     174
Morningside                    188
Upper Lawrenceville            189
Duquesne Heights               191
Esplen                         200
Spring Garden                  219
Name: INCIDENTNEIGHBORHOOD, dtype: int64

According to this, Mt. Olvier Neighborhood has the least amount of arrests, then Troy Hill-Herrs Island, then far followed by Mt. Oliver Boro.

---

## Dataset #3
Since I'm in a group of two, this is part of the work I did for our third dataset.

In [36]:
# importing contract rent data and looking at the first 10 values to get an idea of it
contract_rent_data = pd.read_csv("City of Pittsburgh Contract Rent.csv")

contract_rent_data.head(10)

,_id,Neighborhood,Id,Estimate; Total:,Margin of Error; Total:,Estimate; With cash rent:,Margin of Error; With cash rent:,Estimate; With cash rent: - Less than $100,Margin of Error; With cash rent: - Less than $100,Estimate; With cash rent: - $100 to $149,...,"Estimate; With cash rent: - $1,000 to $1,249","Margin of Error; With cash rent: - $1,000 to $1,249","Estimate; With cash rent: - $1,250 to $1,499","Margin of Error; With cash rent: - $1,250 to $1,499","Estimate; With cash rent: - $1,500 to $1,999","Margin of Error; With cash rent: - $1,500 to $1,999","Estimate; With cash rent: - $2,000 or more","Margin of Error; With cash rent: - $2,000 or more",Estimate; No cash rent,Margin of Error; No cash rent
0,1,Allegheny Center,1,695.0,103.000000,688.0,103.000000,61.0,57.000000,6.0,...,103.0,50.000000,10.0,15.000000,14.0,15.000000,0.0,10.000000,7.0,10.000000
1,2,Allegheny West,2,73.0,33.000000,73.0,33.000000,0.0,10.000000,0.0,...,0.0,10.000000,0.0,10.000000,5.0,8.000000,0.0,10.000000,0.0,10.000000
2,3,Allentown,3,563.0,154.664152,512.0,136.194714,0.0,17.320508,0.0,...,36.0,42.426407,0.0,17.320508,0.0,17.320508,0.0,17.320508,51.0,77.304592
3,4,Arlington,4,216.0,70.469852,211.0,70.469852,0.0,17.320508,0.0,...,0.0,17.320508,6.0,16.763055,0.0,17.320508,0.0,17.320508,5.0,15.779734
4,5,Arlington Heights,5,170.0,69.000000,166.0,70.000000,0.0,10.000000,19.0,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,4.0,6.000000
5,6,Banksville,6,1022.0,221.104048,1015.0,221.104048,0.0,20.000000,0.0,...,45.0,43.416587,0.0,20.000000,0.0,20.000000,0.0,20.000000,7.0,22.271057
6,7,Bedford Dwellings,7,633.0,69.000000,630.0,68.000000,219.0,72.000000,48.0,...,0.0,10.000000,0.0,10.000000,0.0,10.000000,0.0,10.000000,3.0,8.000000
7,8,Beechview,8,1514.0,236.300656,1467.0,234.793526,0.0,31.622777,0.0,...,13.0,36.619667,0.0,31.622777,0.0,31.622777,0.0,31.622777,47.0,41.218928
8,9,Beltzhoover,9,326.0,113.556154,298.0,110.607414,0.0,20.000000,10.0,...,0.0,20.000000,39.0,62.449980,0.0,20.000000,0.0,20.000000,28.0,36.124784
9,10,Bloomfield,10,2990.0,221.682205,2935.0,220.914010,0.0,31.622777,7.0,...,225.0,83.000000,100.0,63.906181,122.0,61.733297,13.0,37.202150,55.0,38.884444

In [53]:
# Calculate the average estimate total for every neighborhood
average_estimates = contract_rent_data.groupby("Neighborhood")["Estimate; Total:"].mean()
average_estimates_sorted = average_estimates.sort_values(ascending=True)

# display values
average_estimates_sorted.head(10)

Neighborhood
Chateau            0.0
New Homestead      4.0
South Shore        8.0
Ridgemont         26.0
Esplen            34.0
Bon Air           46.0
Chartiers City    49.0
St. Clair         52.0
Swisshelm Park    60.0
Allegheny West    73.0
Name: Estimate; Total:, dtype: float64

## Notes

* Chateu has the lowest contract rent average according to this data analysis. 

* According to the data set's website: "Aggregate contract rent is calculated by adding all of the contract rents for occupied housing units in an area. Aggregate contract rent is rounded to the nearest hundred dollars."

* So the reason Chateau showed up as 0 is because the estimated total, which we averaged, was lower than one hundred dollars.